# Generated by Django 5.2.6 on 2025-10-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_tool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='document',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='upload_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='document',
            name='extracted_data',
        ),
        migrations.RemoveField(
            model_name='document',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='document',
            name='vendor_email',
        ),
        migrations.RemoveField(
            model_name='document',
            name='vendor_name',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('po', 'Purchase Order')], max_length=10),
        ),
        migrations.DeleteModel(
            name='DocumentMatch',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
