# Generated by Django 5.2.6 on 2025-10-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching_tool', '0002_remove_item_document_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='UploadedDocument',
        ),
        migrations.RenameField(
            model_name='uploadeddocument',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
    ]
